icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "material-nf"

# [[block]]
# block = "cpu"
# info_cpu = 20
# warning_cpu = 50
# critical_cpu = 90

[[block]]
block = "net"
# Auto-detect the active interface (Wi-Fi or Ethernet)
format = " $icon {$ssid $signal_strength $ip|Wired} "
interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 1
alert = 1
format = " $icon root: $available.eng(w:2) "

# [[block]]
# block = "memory"
# format = " $icon $mem_total_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

# [[block]]
# block = "sound"
# driver = "auto" 
# format = " $icon $volume "

[[block]]
block = "backlight"
device = "amdgpu_bl0" 
format = " $icon $brightness "
# Mouse wheel up/down can increase/decrease brightness
[[block.click]]
button = "up"
action = "increase_brightness"
[[block.click]]
button = "down"
action = "decrease_brightness"

[[block]]
block = "battery"
device = "BAT0"
interval = 30
full_format = " $icon $percentage"
not_charging_format = " $icon $percentage"


[[block]]
block = "time"
interval = 30
format = " $timestamp.datetime(f:'%a %d/%m %R') "

